---
- hosts: 172.31.20.155
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want install webserver
    apt:
      name: apache2
      state: present
 

  - name: i want to copy static files into ansible nodes  side
    copy:
         src: mystaticfile.html
         dest: /var/www/html/index.html


  